import subprocess


def get_arguments_manually():
    s = input("Enter the list of projected attributes (comma-separated): ")
    n = int(input("Enter the number of grouping variables(comma-separated): "))
    v = input("Enter the list of grouping attributes (comma-separated): ")
    f = input(f"Enter list of aggregate functions for the grouping variables (comma-separated): ")
    sigma = [input(f"Enter predicate for grouping variable {i+1}: ") for i in range(n)]
    g = input("Enter predicate for the 'having' clause: ")
    return s, n, v, f, sigma, g

def get_arguments_from_file(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        s = lines[0].strip()
        n = int(lines[1].strip())
        v = lines[2].strip()
        f = lines[3].strip()
        sigma = [line.strip() for line in lines[4:4+n]]
        g = lines[4+n].strip()
    return s, n, v, f, sigma, g

def main(s, n, v, f, sigma, g):
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """
    slt = [item.strip() for item in s.split(',')]
    grouping_attributes = [item.strip() for item in v.split(',')]
    aggregate_functions = [item.strip() for item in f.split(',')]
    predicates = sigma
    having_clause = g


    
    body = f"""
    instances = {{}}
    
    for row in cur:
        # Create a unique key
        attributesFormattedForKey = ""
        hInstan = {{}}
        for x in {grouping_attributes}:
            attributesFormattedForKey += f"{{row[x]}}-"
            hInstan[x] = row[x]
        attributesFormattedForKey = attributesFormattedForKey[:-1]
        #adds placeholder values in H class for aggregate functions
        for y in {aggregate_functions}:
            hInstan[y] = None
        key = attributesFormattedForKey
        if key not in instances:
            instances[key] = H(**hInstan)
    """
    
    groupv =""""""
    select = v + ", " + f
    aggv =""""""
    for x in grouping_attributes:
        groupv += f"""
        
        mysillyobject.{x} = {x}
        """
    for x in aggregate_functions:
        aggv += f"""

        mysillyobject.{x} = {x}
        """
     
    hclass = f"""
    def __init__(mysillyobject, {select}):
        {groupv}
        {aggv}
        
    def printAllClassAttr(abc):
        attrs = vars(abc)
        for attr, value in attrs.items():
            print(f'{{attr}}: {{value}}')
    
    """

    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

class H:
{hclass}
def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect(host = 'localhost', dbname = dbname, user = user, password = password, port = 5432)
    cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    cur.execute("SELECT * FROM sales")
    {body}
    
    table_data = [vars(inst) for inst in instances.values()]
    return tabulate.tabulate(table_data, headers="keys", tablefmt="psql")


def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a filep
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    method = input("Type 'manual' for manual input, or 'file' for file input: ")
    if method.lower() == 'manual':
        args = get_arguments_manually()
    elif method.lower() == 'file':
        filename = input("Enter the filename: ")
        args = get_arguments_from_file(filename)
    else:
        raise ValueError("Invalid input method specified. Use 'manual' or 'file'.")
    main(*args)